name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run one-line script
      run: echo Hello, World!

    - name: Run a multi-line script

      run:
        echo Add other actions to build,
        echo test, and deploy your project
